# Generated by Django 2.1.1 on 2018-09-30 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_auto_20180930_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pics/no-image.jpg', upload_to='profile_pics'),
        ),
    ]
